import type { Report, DuplicateCluster, AreaInsight, DashboardStats } from '@/types';

// Worcester, MA — real neighborhoods and street coordinates
// ─── Demo Reports (25 Worcester-area reports) ─────────────────────────────────
export const DEMO_REPORTS: Report[] = [
  {
    id: '1',
    user_id: null,
    title: 'Large Pothole on Main Street Near City Hall',
    description: 'Deep pothole approximately 2ft wide on Main St just south of City Hall. Vehicles swerving into oncoming lane.',
    image_url: null,
    latitude: 42.2629, longitude: -71.8022,
    address: '455 Main St', neighborhood: 'Downtown',
    category: 'pothole',
    ai_summary: 'Large pothole on high-traffic downtown arterial near City Hall. Multiple vehicles affected daily.',
    urgency_score: 88, impact_score: 84, priority_score: 87,
    priority_level: 'critical',
    status: 'submitted',
    duplicate_cluster_id: 'cluster-1',
    ai_reasoning: 'High urgency due to proximity to City Hall pedestrian traffic and high vehicle volume.',
    recommended_action: 'Prioritize inspection and repair within 24 hours.',
    severity: 'high',
    created_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '2',
    user_id: null,
    title: 'Broken Streetlight Near Grafton Hill Elementary',
    description: 'Streetlight not functioning at corner of Grafton St and Beacon St, near Grafton Hill Elementary. Very dark at night.',
    image_url: null,
    latitude: 42.2558, longitude: -71.7785,
    address: 'Grafton St & Beacon St', neighborhood: 'Grafton Hill',
    category: 'broken_streetlight',
    ai_summary: 'Non-functioning streetlight adjacent to an elementary school creating dangerous nighttime conditions.',
    urgency_score: 95, impact_score: 90, priority_score: 93,
    priority_level: 'critical',
    status: 'under_review',
    duplicate_cluster_id: 'cluster-2',
    ai_reasoning: 'Critical safety hazard — proximity to school and complete darkness creates high risk for children and pedestrians.',
    recommended_action: 'Emergency repair required within 24 hours. Temporary lighting recommended.',
    severity: 'critical',
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '3',
    user_id: null,
    title: 'Cracked Sidewalk Blocking Wheelchair Access on Park Ave',
    description: 'Large crack and raised section on Park Ave sidewalk making it impossible for wheelchair users to pass.',
    image_url: null,
    latitude: 42.2651, longitude: -71.8447,
    address: '890 Park Ave', neighborhood: 'Tatnuck',
    category: 'accessibility_hazard',
    ai_summary: 'Severely damaged sidewalk section creates ADA accessibility violation and safety risk for mobility-impaired residents.',
    urgency_score: 85, impact_score: 80, priority_score: 83,
    priority_level: 'critical',
    status: 'in_progress',
    duplicate_cluster_id: null,
    ai_reasoning: 'ADA compliance issue with direct impact on mobility-impaired community members.',
    recommended_action: 'Temporary accessibility rerouting and schedule urgent repair within 48 hours.',
    severity: 'high',
    created_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '4',
    user_id: null,
    title: 'Illegal Dumping of Appliances on Chandler Street',
    description: 'Several old appliances (refrigerators, mattresses) dumped on the corner of Chandler St and Woodland St.',
    image_url: null,
    latitude: 42.2702, longitude: -71.7908,
    address: 'Chandler St & Woodland St', neighborhood: 'Chandler',
    category: 'illegal_dumping',
    ai_summary: 'Large pile of illegally dumped appliances including refrigerators and mattresses creating public hazard.',
    urgency_score: 68, impact_score: 65, priority_score: 67,
    priority_level: 'high',
    status: 'submitted',
    duplicate_cluster_id: 'cluster-3',
    ai_reasoning: 'Environmental hazard and public nuisance. Refrigerants in old appliances pose chemical risk.',
    recommended_action: 'Schedule bulk waste removal within 3-5 business days.',
    severity: 'medium',
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '5',
    user_id: null,
    title: 'Overflowing Trash Bin at Elm Park',
    description: 'Public trash bin at Elm Park main entrance overflowing for 3 days. Attracting pests and raccoons.',
    image_url: null,
    latitude: 42.2728, longitude: -71.8012,
    address: 'Elm Park, Lincoln St entrance', neighborhood: 'Lincoln Square',
    category: 'trash_overflow',
    ai_summary: 'Overflowing public trash receptacle creating sanitation hazard and pest attraction in high-traffic park area.',
    urgency_score: 55, impact_score: 52, priority_score: 54,
    priority_level: 'medium',
    status: 'resolved',
    duplicate_cluster_id: null,
    ai_reasoning: 'Medium priority sanitation issue. Not an immediate safety hazard but degrades public space quality.',
    recommended_action: 'Schedule immediate collection and increase pickup frequency.',
    severity: 'medium',
    created_at: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '6',
    user_id: null,
    title: 'Road Debris Blocking Lane on Belmont Street',
    description: 'Large pile of fallen tree branches blocking the right lane on Belmont St after last night\'s storm.',
    image_url: null,
    latitude: 42.2699, longitude: -71.7893,
    address: 'Belmont St near Sunderland Rd', neighborhood: 'Chandler',
    category: 'road_obstruction',
    ai_summary: 'Storm debris blocking traffic lane on major arterial road creating collision risk and traffic congestion.',
    urgency_score: 82, impact_score: 78, priority_score: 80,
    priority_level: 'critical',
    status: 'in_progress',
    duplicate_cluster_id: null,
    ai_reasoning: 'Active traffic hazard on high-volume road. Risk of accidents is immediate.',
    recommended_action: 'Emergency clearance required within 2 hours.',
    severity: 'high',
    created_at: new Date(Date.now() - 0.5 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 0.5 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '7',
    user_id: null,
    title: 'Faded Stop Sign on Pleasant Street',
    description: 'Stop sign at corner of Pleasant St and Fruit St is severely faded and barely readable, especially at night.',
    image_url: null,
    latitude: 42.2548, longitude: -71.8098,
    address: 'Pleasant St & Fruit St', neighborhood: 'Main South',
    category: 'broken_sign',
    ai_summary: 'Traffic stop sign severely weathered and unreadable, creating potential traffic safety violation.',
    urgency_score: 58, impact_score: 55, priority_score: 57,
    priority_level: 'medium',
    status: 'assigned',
    duplicate_cluster_id: null,
    ai_reasoning: 'Traffic safety concern. Unreadable stop sign can lead to accidents at intersection.',
    recommended_action: 'Replace sign within 5 business days.',
    severity: 'medium',
    created_at: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '8',
    user_id: null,
    title: 'Pothole Cluster on Shrewsbury Street',
    description: 'Multiple large potholes in a 50-meter stretch on Shrewsbury St near the restaurant district. Road deteriorating rapidly.',
    image_url: null,
    latitude: 42.2681, longitude: -71.7872,
    address: '300-350 Shrewsbury St', neighborhood: 'Shrewsbury Street',
    category: 'pothole',
    ai_summary: 'Cluster of multiple severe potholes on popular restaurant district road indicating systemic infrastructure degradation.',
    urgency_score: 84, impact_score: 88, priority_score: 86,
    priority_level: 'critical',
    status: 'under_review',
    duplicate_cluster_id: 'cluster-1',
    ai_reasoning: 'Multiple reports confirm recurring degradation. High traffic volume from restaurant district amplifies safety risk.',
    recommended_action: 'Full road surface assessment and emergency patching within 48 hours.',
    severity: 'critical',
    created_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '9',
    user_id: null,
    title: 'Pothole Near UMass Memorial Medical Center Entrance',
    description: 'Deep pothole right at the ambulance entrance of UMass Memorial on Lake Ave. Emergency vehicles affected.',
    image_url: null,
    latitude: 42.2760, longitude: -71.7948,
    address: 'UMass Memorial Medical Center, Lake Ave', neighborhood: 'Burncoat',
    category: 'pothole',
    ai_summary: 'Severe pothole at hospital emergency vehicle access point threatening critical emergency response capability.',
    urgency_score: 97, impact_score: 92, priority_score: 95,
    priority_level: 'critical',
    status: 'assigned',
    duplicate_cluster_id: 'cluster-4',
    ai_reasoning: 'Extreme urgency — pothole at hospital entrance directly impacts emergency response times.',
    recommended_action: 'IMMEDIATE repair required. Coordinate with hospital facilities team.',
    severity: 'critical',
    created_at: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '10',
    user_id: null,
    title: 'Missing Manhole Cover on Franklin Street',
    description: 'Manhole cover completely missing on Franklin St near Union Station. Open hole is a serious safety hazard.',
    image_url: null,
    latitude: 42.2617, longitude: -71.7995,
    address: '120 Franklin St', neighborhood: 'Downtown',
    category: 'road_obstruction',
    ai_summary: 'Missing manhole cover creating open road hazard with risk of serious injury to vehicles and pedestrians.',
    urgency_score: 98, impact_score: 90, priority_score: 95,
    priority_level: 'critical',
    status: 'in_progress',
    duplicate_cluster_id: null,
    ai_reasoning: 'Immediate life-safety threat. Open manhole can cause severe injury or vehicle damage.',
    recommended_action: 'EMERGENCY: Barricade immediately and replace cover within 2 hours.',
    severity: 'critical',
    created_at: new Date(Date.now() - 0.25 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 0.1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '11',
    user_id: null,
    title: 'Sidewalk Crack Near Great Brook Valley Bus Stop',
    description: 'Large crack in sidewalk near WRTA bus stop on Plantation St. Elderly residents having trouble navigating.',
    image_url: null,
    latitude: 42.2898, longitude: -71.8195,
    address: 'Plantation St at WRTA Bus Stop', neighborhood: 'Great Brook Valley',
    category: 'damaged_sidewalk',
    ai_summary: 'Significant sidewalk crack adjacent to a bus stop creating trip hazard for transit users including elderly residents.',
    urgency_score: 72, impact_score: 68, priority_score: 71,
    priority_level: 'high',
    status: 'submitted',
    duplicate_cluster_id: null,
    ai_reasoning: 'Bus stop proximity increases daily impact. Elderly and mobility-challenged users at heightened risk.',
    recommended_action: 'Inspect and schedule repair within 3-5 days.',
    severity: 'medium',
    created_at: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '12',
    user_id: null,
    title: 'Streetlight Outage — Downtown Main Street Block',
    description: 'Two streetlights out on Main St between Front St and Foster St. The whole block is very dark.',
    image_url: null,
    latitude: 42.2635, longitude: -71.8018,
    address: 'Main St, Front St to Foster St', neighborhood: 'Downtown',
    category: 'broken_streetlight',
    ai_summary: 'Two consecutive streetlights non-functional creating a dark corridor on main commercial downtown street.',
    urgency_score: 76, impact_score: 72, priority_score: 75,
    priority_level: 'high',
    status: 'under_review',
    duplicate_cluster_id: 'cluster-2',
    ai_reasoning: 'Multiple streetlights out on main commercial corridor increases crime risk and pedestrian safety concerns.',
    recommended_action: 'Repair or replace both fixtures within 48 hours.',
    severity: 'high',
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '13',
    user_id: null,
    title: 'Flooding at Great Brook Valley Underpass',
    description: 'Water accumulation at the underpass on Burncoat St after rain. Road impassable for low vehicles.',
    image_url: null,
    latitude: 42.2905, longitude: -71.8215,
    address: 'Burncoat St Underpass', neighborhood: 'Great Brook Valley',
    category: 'flooding',
    ai_summary: 'Underpass flooding creating impassable road condition and risk of vehicle damage or driver injury.',
    urgency_score: 88, impact_score: 82, priority_score: 86,
    priority_level: 'critical',
    status: 'submitted',
    duplicate_cluster_id: null,
    ai_reasoning: 'Flooding at underpass blocks critical transit route and poses vehicle and pedestrian safety risk.',
    recommended_action: 'Deploy pumping equipment and inspect drainage system immediately.',
    severity: 'high',
    created_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '14',
    user_id: null,
    title: 'Graffiti on Main South Library Branch',
    description: 'Large graffiti tag on the side wall of the Main South branch library on Chandler St.',
    image_url: null,
    latitude: 42.2491, longitude: -71.8062,
    address: 'Chandler Branch Library, Main South', neighborhood: 'Main South',
    category: 'graffiti',
    ai_summary: 'Graffiti vandalism on public library building requiring remediation to maintain community appearance.',
    urgency_score: 28, impact_score: 22, priority_score: 26,
    priority_level: 'low',
    status: 'resolved',
    duplicate_cluster_id: null,
    ai_reasoning: 'Low safety priority but impacts community aesthetics and public property.',
    recommended_action: 'Schedule graffiti removal within 2 weeks.',
    severity: 'low',
    created_at: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '15',
    user_id: null,
    title: 'Pothole Worsening on Highland Street',
    description: 'Pothole on Highland St near Holy Cross has doubled in size after last week\'s rain. Very dangerous for cyclists.',
    image_url: null,
    latitude: 42.2580, longitude: -71.8220,
    address: '800 Highland St', neighborhood: 'Tatnuck',
    category: 'pothole',
    ai_summary: 'Rapidly expanding pothole on mixed-use road with bicycle lane. Active worsening indicates sub-base failure.',
    urgency_score: 80, impact_score: 76, priority_score: 79,
    priority_level: 'high',
    status: 'submitted',
    duplicate_cluster_id: 'cluster-1',
    ai_reasoning: 'Expanding pothole suggests deeper infrastructure issue. Cycling lane proximity increases injury risk.',
    recommended_action: 'Sub-base inspection and comprehensive repair within 48 hours.',
    severity: 'high',
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '16',
    user_id: null,
    title: 'Broken Bench at Green Hill Park',
    description: 'Park bench with broken slats and exposed nails near the playground at Green Hill Park. Children playing nearby.',
    image_url: null,
    latitude: 42.2798, longitude: -71.7850,
    address: 'Green Hill Park, Skyline Dr', neighborhood: 'Burncoat',
    category: 'other',
    ai_summary: 'Damaged park bench with exposed sharp components near children\'s play area creating injury risk.',
    urgency_score: 52, impact_score: 45, priority_score: 49,
    priority_level: 'medium',
    status: 'submitted',
    duplicate_cluster_id: null,
    ai_reasoning: 'Moderate priority due to exposed nails near children\'s play area.',
    recommended_action: 'Remove or barricade bench and schedule replacement within 1 week.',
    severity: 'medium',
    created_at: new Date(Date.now() - 9 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 9 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '17',
    user_id: null,
    title: 'Illegal Dumping — Main South Alley',
    description: 'Construction waste illegally dumped in alley off Southgate St in Main South, blocking resident access.',
    image_url: null,
    latitude: 42.2478, longitude: -71.8055,
    address: 'Southgate St alley, Main South', neighborhood: 'Main South',
    category: 'illegal_dumping',
    ai_summary: 'Large construction waste dump in residential alley blocking access and creating environmental hazard.',
    urgency_score: 62, impact_score: 60, priority_score: 61,
    priority_level: 'high',
    status: 'under_review',
    duplicate_cluster_id: 'cluster-3',
    ai_reasoning: 'Construction debris blocking residential access. Potential hazardous materials require investigation.',
    recommended_action: 'Investigate source and schedule removal within 3 days.',
    severity: 'medium',
    created_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '18',
    user_id: null,
    title: 'Broken Traffic Signal — Kelley Square',
    description: 'Traffic light at Kelley Square cycling incorrectly — a notoriously complex intersection now showing conflicting signals.',
    image_url: null,
    latitude: 42.2563, longitude: -71.8085,
    address: 'Kelley Square, Main St & Millbury St', neighborhood: 'Downtown',
    category: 'road_obstruction',
    ai_summary: 'Malfunctioning traffic signal at Kelley Square simultaneously showing green in conflicting directions — critical collision risk.',
    urgency_score: 99, impact_score: 95, priority_score: 97,
    priority_level: 'critical',
    status: 'in_progress',
    duplicate_cluster_id: null,
    ai_reasoning: 'CRITICAL: Kelley Square is one of Worcester\'s most complex intersections. Signal failure is a direct collision hazard.',
    recommended_action: 'EMERGENCY: Deploy traffic control officer immediately and dispatch signal repair team.',
    severity: 'critical',
    created_at: new Date(Date.now() - 0.1 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 0.05 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '19',
    user_id: null,
    title: 'Damaged Sidewalk Near Great Brook Valley School',
    description: 'Buckled and cracked sidewalk along Great Brook Valley Early Childhood Center drop-off zone.',
    image_url: null,
    latitude: 42.2888, longitude: -71.8188,
    address: 'Great Brook Valley Early Childhood Center', neighborhood: 'Great Brook Valley',
    category: 'damaged_sidewalk',
    ai_summary: 'Severely damaged sidewalk in school drop-off zone creates daily trip hazard for children and parents.',
    urgency_score: 82, impact_score: 80, priority_score: 81,
    priority_level: 'critical',
    status: 'submitted',
    duplicate_cluster_id: null,
    ai_reasoning: 'School proximity and child safety makes this high priority.',
    recommended_action: 'Emergency repair before next school day.',
    severity: 'high',
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '20',
    user_id: null,
    title: 'Trash Overflow — Shrewsbury Street Restaurant Row',
    description: 'Bins behind restaurants on Shrewsbury St overflowing with food waste. Smell is unbearable.',
    image_url: null,
    latitude: 42.2675, longitude: -71.7865,
    address: 'Shrewsbury St Restaurant District', neighborhood: 'Shrewsbury Street',
    category: 'trash_overflow',
    ai_summary: 'Commercial food waste overflow in popular restaurant district creating sanitation and pest control issues.',
    urgency_score: 60, impact_score: 55, priority_score: 58,
    priority_level: 'medium',
    status: 'resolved',
    duplicate_cluster_id: null,
    ai_reasoning: 'Sanitation issue in commercial area. Health hazard potential if not addressed.',
    recommended_action: 'Commercial sanitation enforcement notice and immediate collection.',
    severity: 'medium',
    created_at: new Date(Date.now() - 12 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '21',
    user_id: null,
    title: 'Pothole — Great Brook Valley Residential Street',
    description: 'Deep pothole on Tacoma St in Great Brook Valley residential area. Has been there for 3 weeks with no response.',
    image_url: null,
    latitude: 42.2880, longitude: -71.8175,
    address: '45 Tacoma St', neighborhood: 'Great Brook Valley',
    category: 'pothole',
    ai_summary: 'Persistent pothole on residential road unaddressed for over 3 weeks in underserved neighborhood.',
    urgency_score: 65, impact_score: 58, priority_score: 62,
    priority_level: 'high',
    status: 'submitted',
    duplicate_cluster_id: 'cluster-4',
    ai_reasoning: 'Time unresolved increases urgency. Great Brook Valley has historically high unresolved issue rates.',
    recommended_action: 'Schedule repair and review area for additional road maintenance needs.',
    severity: 'medium',
    created_at: new Date(Date.now() - 21 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 21 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '22',
    user_id: null,
    title: 'Broken Streetlight — Grafton Hill Walking Path',
    description: 'Streetlight along the Grafton Hill trail off Grafton St has been out for 2 weeks. Unsafe at night.',
    image_url: null,
    latitude: 42.2545, longitude: -71.7775,
    address: 'Grafton Hill Trail, Grafton St', neighborhood: 'Grafton Hill',
    category: 'broken_streetlight',
    ai_summary: 'Park pathway lighting outage creating unsafe conditions for evening recreational users.',
    urgency_score: 70, impact_score: 65, priority_score: 68,
    priority_level: 'high',
    status: 'submitted',
    duplicate_cluster_id: 'cluster-2',
    ai_reasoning: '2-week outage suggests maintenance backlog. Path users face elevated risk after dark.',
    recommended_action: 'Schedule repair within 48 hours. Install temporary lighting if delayed.',
    severity: 'medium',
    created_at: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '23',
    user_id: null,
    title: 'Water Main Leak — Polar Park Area',
    description: 'Water bubbling up through road surface on Madison St near Polar Park. Possible water main break.',
    image_url: null,
    latitude: 42.2565, longitude: -71.8095,
    address: 'Madison St near Polar Park', neighborhood: 'Downtown',
    category: 'flooding',
    ai_summary: 'Suspected water main leak with surface water emergence near Polar Park stadium on game days.',
    urgency_score: 90, impact_score: 85, priority_score: 88,
    priority_level: 'critical',
    status: 'in_progress',
    duplicate_cluster_id: null,
    ai_reasoning: 'Potential infrastructure failure. Water main leaks can lead to sinkholes and road collapse.',
    recommended_action: 'Contact utilities emergency line immediately. Cordon off area.',
    severity: 'critical',
    created_at: new Date(Date.now() - 0.5 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 0.25 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '24',
    user_id: null,
    title: 'Damaged Sidewalk — Main South Senior Housing',
    description: 'Collapsed sidewalk section outside Plumley Village senior housing on Austin St. Residents cannot safely exit.',
    image_url: null,
    latitude: 42.2505, longitude: -71.8070,
    address: 'Plumley Village, Austin St', neighborhood: 'Main South',
    category: 'accessibility_hazard',
    ai_summary: 'Collapsed sidewalk blocking primary exit of senior housing facility creating immediate accessibility emergency.',
    urgency_score: 94, impact_score: 92, priority_score: 93,
    priority_level: 'critical',
    status: 'under_review',
    duplicate_cluster_id: null,
    ai_reasoning: 'Critical: elderly residents cannot safely exit facility. ADA emergency in underserved neighborhood.',
    recommended_action: 'IMMEDIATE emergency repair. Coordinate with facility for temporary access solutions.',
    severity: 'critical',
    created_at: new Date(Date.now() - 1.5 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 0.5 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '25',
    user_id: null,
    title: 'Graffiti — Great Brook Valley Underpass',
    description: 'Extensive graffiti covering the underpass walls on Plantation St. Been there for months with no cleanup.',
    image_url: null,
    latitude: 42.2910, longitude: -71.8205,
    address: 'Plantation St Underpass', neighborhood: 'Great Brook Valley',
    category: 'graffiti',
    ai_summary: 'Extensive long-standing graffiti on public infrastructure in Great Brook Valley underpass.',
    urgency_score: 22, impact_score: 18, priority_score: 20,
    priority_level: 'low',
    status: 'submitted',
    duplicate_cluster_id: null,
    ai_reasoning: 'Low safety risk but persistent neglect in Great Brook Valley contributes to neighborhood perception of abandonment.',
    recommended_action: 'Schedule graffiti abatement as part of routine Great Brook Valley improvement plan.',
    severity: 'low',
    created_at: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '26',
    user_id: null,
    title: 'Missing Curb Cut on Lincoln Street — Wheelchair Users Blocked',
    description: 'No curb cut at Lincoln St & Beacon St. Wheelchair users are forced into traffic to cross. Multiple complaints from residents.',
    image_url: null,
    latitude: 42.2726, longitude: -71.8043,
    address: 'Lincoln St & Beacon St', neighborhood: 'Lincoln Square',
    category: 'accessibility_hazard',
    ai_summary: 'Missing ADA curb cut forces mobility-impaired residents into active traffic lanes at busy intersection.',
    urgency_score: 86, impact_score: 83, priority_score: 85,
    priority_level: 'critical',
    status: 'submitted',
    duplicate_cluster_id: null,
    ai_reasoning: 'ADA violation at signalized intersection with high pedestrian volume. Wheelchair users diverted into moving traffic daily.',
    recommended_action: 'Install temporary ramp and schedule permanent ADA curb cut within 30 days.',
    severity: 'high',
    created_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '27',
    user_id: null,
    title: 'Pothole Cluster on Cambridge Street Near Rotary',
    description: 'Four large potholes in a row on Cambridge St approaching the Lincoln Square rotary. Caused a blowout to a delivery truck.',
    image_url: null,
    latitude: 42.2731, longitude: -71.8061,
    address: '450 Cambridge St', neighborhood: 'Lincoln Square',
    category: 'pothole',
    ai_summary: 'Multiple severe potholes on arterial approach to busy rotary intersection. Confirmed vehicle damage reported.',
    urgency_score: 88, impact_score: 85, priority_score: 87,
    priority_level: 'critical',
    status: 'under_review',
    duplicate_cluster_id: 'cluster-1',
    ai_reasoning: 'Confirmed vehicle damage and high rotary traffic volume amplify injury risk. Cluster pattern suggests base layer failure.',
    recommended_action: 'Emergency patching and full road surface assessment within 48 hours.',
    severity: 'critical',
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '28',
    user_id: null,
    title: 'Overflowing Trash Bins — Cristoforo Columbus Park',
    description: 'Both trash bins at Cristoforo Columbus Park are overflowing. Garbage has spilled onto the walking path. Raccoons seen.',
    image_url: null,
    latitude: 42.2684, longitude: -71.7880,
    address: 'Cristoforo Columbus Park, Shrewsbury St', neighborhood: 'Shrewsbury Street',
    category: 'trash_overflow',
    ai_summary: 'Overflow trash conditions in neighborhood park creating sanitation hazard and wildlife attraction.',
    urgency_score: 54, impact_score: 50, priority_score: 52,
    priority_level: 'medium',
    status: 'submitted',
    duplicate_cluster_id: null,
    ai_reasoning: 'Medium sanitation priority. Park visitor experience degraded and pest attraction risk.',
    recommended_action: 'Immediate collection and increase pickup schedule for this location.',
    severity: 'medium',
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '29',
    user_id: null,
    title: 'Streetlight Out Near Vernon Hill School',
    description: 'Streetlight pole at the corner of Vernon Hill Ave and Enfield St is dark. Kids walk this route home after school activities.',
    image_url: null,
    latitude: 42.2493, longitude: -71.7858,
    address: 'Vernon Hill Ave & Enfield St', neighborhood: 'Vernon Hill',
    category: 'broken_streetlight',
    ai_summary: 'Non-functioning streetlight on a school-adjacent pedestrian route creating after-dark safety risk for children.',
    urgency_score: 91, impact_score: 88, priority_score: 90,
    priority_level: 'critical',
    status: 'under_review',
    duplicate_cluster_id: 'cluster-2',
    ai_reasoning: 'Child pedestrian safety on school route. Consistent after-school darkness raises risk of traffic incidents.',
    recommended_action: 'Emergency repair required within 24 hours.',
    severity: 'critical',
    created_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '30',
    user_id: null,
    title: 'Flooded Intersection at Green Street and Sycamore',
    description: 'Storm drain completely blocked — Green St and Sycamore St intersection is a lake after any rain. Cars stalling out.',
    image_url: null,
    latitude: 42.2609, longitude: -71.8341,
    address: 'Green St & Sycamore St', neighborhood: 'Tatnuck',
    category: 'flooding',
    ai_summary: 'Clogged storm drain causing repeated intersection flooding after rainfall with vehicle stall-out incidents.',
    urgency_score: 87, impact_score: 80, priority_score: 84,
    priority_level: 'critical',
    status: 'in_progress',
    duplicate_cluster_id: null,
    ai_reasoning: 'Repeated flooding after rain events indicates persistent drainage failure. Vehicle damage and pedestrian risk.',
    recommended_action: 'Inspect and clear storm drain. Assess drainage infrastructure.',
    severity: 'high',
    created_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 0.5 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '31',
    user_id: null,
    title: 'Graffiti on Vernon Hill Community Center Exterior',
    description: 'Spray painted tags on the south wall of Vernon Hill Community Center on Enfield St. Has been there about two weeks.',
    image_url: null,
    latitude: 42.2488, longitude: -71.7849,
    address: 'Vernon Hill Community Center, Enfield St', neighborhood: 'Vernon Hill',
    category: 'graffiti',
    ai_summary: 'Graffiti vandalism on community center building in residential neighborhood.',
    urgency_score: 25, impact_score: 20, priority_score: 23,
    priority_level: 'low',
    status: 'submitted',
    duplicate_cluster_id: null,
    ai_reasoning: 'Low safety risk. Community morale impact on neighborhood gathering space.',
    recommended_action: 'Schedule graffiti removal within 2 weeks during routine maintenance.',
    severity: 'low',
    created_at: new Date(Date.now() - 13 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 13 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '32',
    user_id: null,
    title: 'Buckled Sidewalk on Salisbury Street',
    description: 'Tree root has pushed up a large sidewalk section on Salisbury St near the library. 4-inch rise — very easy to trip over.',
    image_url: null,
    latitude: 42.2719, longitude: -71.8038,
    address: '870 Salisbury St', neighborhood: 'Lincoln Square',
    category: 'damaged_sidewalk',
    ai_summary: 'Tree root heave creating severe trip hazard on residential sidewalk with 4-inch vertical displacement.',
    urgency_score: 71, impact_score: 66, priority_score: 69,
    priority_level: 'high',
    status: 'submitted',
    duplicate_cluster_id: 'cluster-5',
    ai_reasoning: 'Significant vertical displacement at 4 inches exceeds trip hazard threshold. High pedestrian usage near library.',
    recommended_action: 'Grind or replace affected sidewalk panel. Assess root system impact.',
    severity: 'medium',
    created_at: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '33',
    user_id: null,
    title: 'Sinkhole Opening on Millbury Street Near Kelley Square',
    description: 'Small sinkhole appearing on Millbury St, about 1 ft wide and growing. Asphalt cracking outward. Possible sewer collapse.',
    image_url: null,
    latitude: 42.2561, longitude: -71.8075,
    address: '15 Millbury St', neighborhood: 'Downtown',
    category: 'road_obstruction',
    ai_summary: 'Developing sinkhole with outward asphalt cracking indicating possible underground sewer infrastructure failure.',
    urgency_score: 96, impact_score: 91, priority_score: 94,
    priority_level: 'critical',
    status: 'assigned',
    duplicate_cluster_id: null,
    ai_reasoning: 'Sinkhole near Kelley Square poses imminent collapse risk to vehicles and pedestrians. Potential major infrastructure failure.',
    recommended_action: 'EMERGENCY: Barricade immediately. Dispatch engineering team. Contact DPW sewer division.',
    severity: 'critical',
    created_at: new Date(Date.now() - 0.3 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 0.1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '34',
    user_id: null,
    title: 'Illegal Tire Dumping Near Great Brook Valley Soccer Field',
    description: 'Over 20 tires dumped in the woods adjacent to the soccer field off Plantation St. Strong smell and mosquito breeding concern.',
    image_url: null,
    latitude: 42.2920, longitude: -71.8210,
    address: 'Great Brook Valley Soccer Field, Plantation St', neighborhood: 'Great Brook Valley',
    category: 'illegal_dumping',
    ai_summary: 'Large-scale illegal tire dumping near recreational area creating environmental and public health hazard.',
    urgency_score: 70, impact_score: 68, priority_score: 69,
    priority_level: 'high',
    status: 'submitted',
    duplicate_cluster_id: null,
    ai_reasoning: 'Standing water in tires is a mosquito breeding hazard. Large-scale dump near family recreational area requires prompt remediation.',
    recommended_action: 'Report to DEP for illegal dumping investigation. Schedule tire removal within 5 days.',
    severity: 'medium',
    created_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '35',
    user_id: null,
    title: 'Damaged Sidewalk Outside Lincoln Square YMCA',
    description: 'Cracked and uneven sidewalk panels in front of the YMCA on Ionic Ave. Used heavily by gym members and school groups.',
    image_url: null,
    latitude: 42.2724, longitude: -71.8055,
    address: 'YMCA, Ionic Ave, Lincoln Square', neighborhood: 'Lincoln Square',
    category: 'damaged_sidewalk',
    ai_summary: 'Multiple damaged sidewalk panels at high-traffic YMCA entrance creating trip hazard for daily gym and youth program users.',
    urgency_score: 68, impact_score: 63, priority_score: 66,
    priority_level: 'high',
    status: 'submitted',
    duplicate_cluster_id: 'cluster-5',
    ai_reasoning: 'High foot traffic from YMCA including youth programs increases injury risk from damaged surface.',
    recommended_action: 'Replace damaged panels and inspect adjacent sections within one week.',
    severity: 'medium',
    created_at: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
  },
];

// ─── Demo Clusters ────────────────────────────────────────────────────────────
export const DEMO_CLUSTERS: DuplicateCluster[] = [
  {
    id: 'cluster-1',
    category: 'pothole',
    center_latitude: 42.2630,
    center_longitude: -71.8020,
    cluster_size: 4,
    status: 'submitted',
    neighborhood: 'Downtown / Lincoln Square',
    created_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'cluster-2',
    category: 'broken_streetlight',
    center_latitude: 42.2600,
    center_longitude: -71.7900,
    cluster_size: 4,
    status: 'under_review',
    neighborhood: 'Grafton Hill / Vernon Hill',
    created_at: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'cluster-3',
    category: 'illegal_dumping',
    center_latitude: 42.2485,
    center_longitude: -71.8058,
    cluster_size: 2,
    status: 'under_review',
    neighborhood: 'Main South',
    created_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'cluster-4',
    category: 'pothole',
    center_latitude: 42.2820,
    center_longitude: -71.7949,
    cluster_size: 2,
    status: 'assigned',
    neighborhood: 'Burncoat / Great Brook Valley',
    created_at: new Date(Date.now() - 21 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'cluster-5',
    category: 'damaged_sidewalk',
    center_latitude: 42.2722,
    center_longitude: -71.8047,
    cluster_size: 2,
    status: 'submitted',
    neighborhood: 'Lincoln Square',
    created_at: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
  },
];

// ─── Demo Area Insights ───────────────────────────────────────────────────────
export const DEMO_INSIGHTS: AreaInsight[] = [
  {
    id: 'ins-1',
    neighborhood: 'Great Brook Valley',
    total_reports: 7,
    unresolved_reports: 7,
    avg_priority_score: 68,
    avg_resolution_days: 26.1,
    equity_flag: true,
    equity_score: 94,
    top_issues: ['pothole', 'damaged_sidewalk', 'illegal_dumping'],
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ins-2',
    neighborhood: 'Main South',
    total_reports: 5,
    unresolved_reports: 4,
    avg_priority_score: 55,
    avg_resolution_days: 18.2,
    equity_flag: true,
    equity_score: 78,
    top_issues: ['illegal_dumping', 'graffiti', 'broken_sign'],
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ins-3',
    neighborhood: 'Downtown',
    total_reports: 7,
    unresolved_reports: 6,
    avg_priority_score: 85,
    avg_resolution_days: 3.2,
    equity_flag: false,
    equity_score: 38,
    top_issues: ['road_obstruction', 'flooding', 'pothole'],
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ins-4',
    neighborhood: 'Grafton Hill',
    total_reports: 3,
    unresolved_reports: 2,
    avg_priority_score: 58,
    avg_resolution_days: 8.5,
    equity_flag: false,
    equity_score: 48,
    top_issues: ['broken_streetlight', 'pothole', 'damaged_sidewalk'],
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ins-5',
    neighborhood: 'Lincoln Square',
    total_reports: 4,
    unresolved_reports: 4,
    avg_priority_score: 77,
    avg_resolution_days: 0,
    equity_flag: true,
    equity_score: 82,
    top_issues: ['pothole', 'damaged_sidewalk', 'accessibility_hazard'],
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ins-6',
    neighborhood: 'Vernon Hill',
    total_reports: 2,
    unresolved_reports: 2,
    avg_priority_score: 57,
    avg_resolution_days: 0,
    equity_flag: true,
    equity_score: 75,
    top_issues: ['broken_streetlight', 'graffiti'],
    updated_at: new Date().toISOString(),
  },
];

// ─── Demo Dashboard Stats ─────────────────────────────────────────────────────
export const DEMO_STATS: DashboardStats = {
  total_reports: 35,
  open_reports: 30,
  resolved_reports: 3,
  high_priority_reports: 22,
  duplicate_clusters: 5,
  avg_resolution_days: 6.8,
  reports_this_week: 18,
  resolution_rate: 9,
};

// ─── Demo trend data (last 14 days) ──────────────────────────────────────────
export const DEMO_TRENDS = Array.from({ length: 14 }, (_, i) => {
  const date = new Date();
  date.setDate(date.getDate() - (13 - i));
  return {
    date: date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
    submitted: Math.floor(Math.random() * 5) + 1,
    resolved: Math.floor(Math.random() * 3),
  };
});

export const DEMO_CATEGORY_BREAKDOWN = [
  { category: 'Pothole', count: 6, fill: '#EF4444' },
  { category: 'Broken Streetlight', count: 5, fill: '#F97316' },
  { category: 'Road Obstruction', count: 5, fill: '#EAB308' },
  { category: 'Damaged Sidewalk', count: 5, fill: '#F59E0B' },
  { category: 'Accessibility Hazard', count: 3, fill: '#3B82F6' },
  { category: 'Illegal Dumping', count: 3, fill: '#22C55E' },
  { category: 'Flooding', count: 3, fill: '#6366F1' },
  { category: 'Trash Overflow', count: 3, fill: '#84CC16' },
  { category: 'Graffiti', count: 3, fill: '#8B5CF6' },
];
